nome = input("Digite o seu nome : ")
sobreNome = input("Digite o seu sobrenome :")
idade = input("Digite a sua idade :")
esporte = input("Digite o seu esporte favorito :")
pet = input("Digite a raça do seu animal preferido :")
print("O meu nome completo é  : ", nome , sobreNome)
print("A minha idade é : ", idade)
print("O meu esporte favorito é : ", esporte)
print(f"O meu animal preferido é  : {pet}")